language: smalltalk
sudo: false

os:
- linux
- osx

smalltalk:
  - Pharo-7.0
  - Pharo-6.1
  - Pharo64-7.0
  - Pharo64-6.1

matrix:
  fast_finish: true
  allow_failures:
    - smalltalk: Pharo-7.0
    - smalltalk: Pharo64-7.0